{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Que 1 - What is the difference between interpreted and complied languages?\n",
        "\n",
        "Ans - Interpreted language is a type of  programming language for which most of its implementation execute instructions directly and freely, without previously compiling a program into machine-language instructions. Complied language is a programming language whose implementations are typically compilers which converts the source code to machine code.\n",
        "\n",
        "\n",
        "Que2 - What is exception handling in python ?\n",
        "\n",
        "Ans- In python, an exception is an event that occurs during programme execution that distrupts the regular flow of code.\n",
        "\n",
        "Que3-  What is the purpose of the finally block in exception handling ?\n",
        "\n",
        "Ans- The purpose of the finally block in exception handling is to write code that must be executed regardless of whether the try block generates an error.\n",
        "\n",
        "Que4- What is logging in python ?\n",
        "\n",
        "Ans- Logging in python is a crucial aspect of the coding process since it allows to keep track of everything that happens when run the code. Logging facilitates code monitoring, troubleshooting and debugging.\n",
        "\n",
        "Que5-  What is the significance of the _ _ del _ _ method in python ?\n",
        "\n",
        "Ans- The _ _ del _ _ method in python , also known as the destructor, is a special method that is called by the garbage collector when an object to be destroyed. Its primary significance lies in allowing an object to perform cleanup operations before it is removed from memory.\n",
        "\n",
        "Que6- What is the difference between import and from ...import in python ?\n",
        "\n",
        "Ans- The import statement is used to import a module or a module's attribute into the current namespace whereas from ...import statement is used to import specific attributes from a module into the current namespace.\n",
        "\n",
        "Que- 7- How can you handle multiple exceptions in python ?\n",
        "\n",
        "Ans- We can handle multiple exceptions in python with a single exception block. In an except clause, we can use a tuple of values to define several exceptions.\n",
        "\n",
        "Que8- What is the purpose of the with statement when handling files in python ?\n",
        "\n",
        "Ans- The purpose of the with statement when handling files in python to ensures that the file is closed properly after the block of code is executed.\n",
        "\n",
        "Que9-  What is the difference between multithreading and multiprocessing ?\n",
        "\n",
        "Ans- Multithreading - It is a technique where multiple threads are generated by a single process at the same time and implements concurrency. Multiprocessing - It is a\n",
        "technique where multiple processes run across multiple cores at the same time and implements parallelism.\n",
        "\n",
        "Que10 - What are the advantages of using logging in a program ?\n",
        "\n",
        "ans- The advantages of using logging in a program as it records the state and flow of program and shows how program behaves overtime.\n",
        "\n",
        "Que11-  What is memory mangement in python ?\n",
        "\n",
        "Ans- Memory management in python is the process of allocating and dealing with memory so that the program can run efficiently. One advantage to python, compared to other programming languages, is that it can perform memory management tasks automatically.\n",
        "\n",
        "Que12 - What are the basics steps involved in exception handling in python ?\n",
        "\n",
        "Ans- The basics steps involved in exception handling in python are:\n",
        "\n",
        "1.\n",
        "Use try and except block : To handle exceptions, we must utilise the try and except blocks. Define dangerous code that can throw an exception inside the try block and related handling code inside the except block.\n",
        "\n",
        "2.\n",
        "Using try with finally : The finally block in python is used in conjucation with the try block statement. The finally block is used to write code that must be excecuted regardless of whether the try block generates an error.\n",
        "\n",
        "3.\n",
        "Use try with else : Use the else statement in conjucation with try block. If want to run a specific code only if an exception is not produced.\n",
        "\n",
        "Que13- Why is memory management important in python ?\n",
        "\n",
        "Ans- Memory management important in python because it improves performance, scalability and reliability, even in a language that handles much of it automatically.\n",
        "\n",
        "Que14- What is the role of try and except in exception handling ?\n",
        "\n",
        "ans- The role of try and except in exception handling is to allow to catch and handle errors gracefully without crashing the program. The try block contains code that might raise an exception and the except block catches and handles the exception if one occurs.\n",
        "\n",
        "Que15- How does python's garbage collection system work ?\n",
        "\n",
        "Python's garbage collection system work by automatically cleans up any unused objects based on reference counting and object allocation and deallocation. This also helps periodically clear up memory space to help a program run more smoothly.\n",
        "\n",
        "Que16- What is the purpose of the else block in exception handling ?\n",
        "\n",
        "Ans- The purpose of the else block in exception handling is to help when the code didn't enter the exception block. It separates the normal logic that should run only when everything goes well in the try block.\n",
        "\n",
        "Que17- What are the common logging levels in python ?\n",
        "\n",
        "Ans- The common logging levels in python are -\n",
        "\n",
        "1.\n",
        "DEBUG : To give detailed information of any variable, message while doing debugging.\n",
        "\n",
        "2.\n",
        "INFO : This is used to convey that the code is working as expected.\n",
        "\n",
        "3.\n",
        "WARNING : Used to indicate that something unexpected happened or potential issues in code.\n",
        "\n",
        "4.\n",
        "ERROR : Serious problem with some function.\n",
        "\n",
        "5.\n",
        "CRITICAL : Terminal of program/code/software.\n",
        "\n",
        "Que18- What is the difference between os.fork() and multiprocessing in python ?\n",
        "\n",
        "Ans- os.fork(): This is system call that creates a new process by duplicating the calling process. The new process is an almost exact copy of parent process. This is low-level way to create processes and is only available in Unix-like systems.\n",
        "\n",
        "\n",
        "Multiprocessing: This is the higher level, cross-platform module in python that provides an API for creating and managing processes. It is generally preffered way to achieve parrallelism in python or various opearting systems.\n",
        "\n",
        "Ans19- What is the importance of closing a file in python ?\n",
        "\n",
        "Ans- The importance of closing a file in python is an essential practice that helps maintain data integrity, prevent resource leaks and ensure the reliability of the program.\n",
        "\n",
        "Que20- What is the difference between file.read() and file.readline() in python ?\n",
        "\n",
        "Ans-f.read() will read everything from starting whereas file.readline() will only read the first line.\n",
        "\n",
        "Que21- What is the logging module in python used for ?\n",
        "\n",
        "Ans- The logging module in python is used for providing a flexible and powerful framework for emitting log messages from applications.\n",
        "\n",
        "Que22- What is the os module in python used for in file handling ?\n",
        "\n",
        "Ans- The os module in python used for in file handling as it provides functionality to interact with the operating system.\n",
        "\n",
        "Que23- What are the challenges associated with memory management in python ?\n",
        "\n",
        "Ans- The challenges associated with memory management in python are:\n",
        "\n",
        "1.Global Interpreter Lock ( GIL) Python(specifically CPython) uses a Global Interpreter Lock, which restricts execution to one thread at a time, even on multi-core processsors. This limits true parrallelism in memory-intensive, multi-threade applications.\n",
        "\n",
        "2.Although Python has automatic garbage collection, memory leaks can still happen due to unintentional and circular references that the garbage collector does not clean up efficiency.\n",
        "\n",
        "Que24- How do you raise an exception manually in python ?\n",
        "\n",
        "Ans- We can raise an exception manually in python by using the raise statement. This is useful when you want to trigger an error intentionally, for example , to enforce a rule or validate input.\n",
        "\n",
        "Que25- Why is it important to use multithreading in certain applications ?\n",
        "\n",
        "Ans- It is important to use multithreading in certain applications as it provides some key benefits such as improved performance, utilization of resource, enhanced responsiveness, concurrency, efficient data sharing and specialization in task division\n"
      ],
      "metadata": {
        "id": "hSdteKQU1Tas"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "A#1 How can you open a file for writing in pthon and write a string in it.\n",
        "\n",
        "with open(\"file.txt\", \"w\") as f:\n",
        "  f.write (\"hello,world!\")\n",
        "with open(\"file.txt\", \"r\") as f:\n",
        "  line=f.read()\n",
        "  print(line)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hXjpFr4KlWdg",
        "outputId": "59c7fb86-2ec0-4fab-887a-dc7505b31d3b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "hello,world!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#2 Write a python program to read the contents of a file and print each line.\n",
        "file = open(\"test.txt\",\"w\")\n",
        "file.write(\"This is the test file1\\n\")\n",
        "file.write(\"This is the test file2\\n\")\n",
        "\n",
        "file.write(\"This is the test file3\\n\")\n",
        "file = open(\"test.txt\",\"r\")\n",
        "file.seek(0)\n",
        "print(file.read())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "MyjaXMDql4Av",
        "outputId": "d7ebf9c7-9824-48cb-fe20-9229ac172703"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "This is the test file1\n",
            "This is the test file2\n",
            "This is the test file3\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#3 How would you handle a case where the file doesn't exit while trying to open it for reading?\n",
        "from os import error\n",
        "fname= \"f.txt\"\n",
        "try:\n",
        "  with open(\"f.txt\",\"r\")as f:\n",
        "    line= f.read()\n",
        "except FileNotFoundError:\n",
        "  print(f\"Error :file'{fname}'' does not exit.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "UWWFeAYImu8f",
        "outputId": "9b4a5b87-5ed4-4044-f5c1-6eb3e61698a9"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Error :file'f.txt'' does not exit.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#4 Write a python script that reads from one fifle and writes its content to another file.\n",
        "\n",
        "with open(\"test.txt\", \"r\") as f:\n",
        "  data = f. read()\n",
        "\n",
        "with open(\"new.txt\", \"w\") as f:\n",
        "  f.write(data)\n",
        "\n",
        "with open(\"new.txt\", \"r\") as f:\n",
        "  print(f.read())"
      ],
      "metadata": {
        "id": "J6tKAlWsm64u",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "89870005-abc7-473e-b3fc-9c19f12864cb"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "This is the test file1\n",
            "This is the test file2\n",
            "This is the test file3\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#5 How would you catch and handle division by zero error in python?\n",
        "\n",
        "try:\n",
        "  10/0\n",
        "except ZeroDivisionError as e:\n",
        "  print(\"I am handling zero division error\", e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3FxK8zpILun_",
        "outputId": "5ca14d2d-d664-41aa-a29d-ad39079706d8"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "I am handling zero division error division by zero\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#6 Write a python program that logs and error message to a log file when division by zero exception occurs.\n",
        "\n",
        "import logging\n",
        "logging.basicConfig(filename = \"program.log\", level= logging.DEBUG)\n",
        "try:\n",
        "  10/0\n",
        "except ZeroDivisionError as e:\n",
        "  logging.error(\"I am handling zero division error\", e)\n",
        ""
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0KAPZjQrMedu",
        "outputId": "745fb4e4-7ab2-414d-eb33-e7f3d7d7433f"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"/tmp/ipython-input-9-2758751736.py\", line 6, in <cell line: 0>\n",
            "    10/0\n",
            "    ~~^~\n",
            "ZeroDivisionError: division by zero\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
            "    msg = self.format(record)\n",
            "          ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/logging/__init__.py\", line 953, in format\n",
            "    return fmt.format(record)\n",
            "           ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/logging/__init__.py\", line 687, in format\n",
            "    record.message = record.getMessage()\n",
            "                     ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
            "    msg = msg % self.args\n",
            "          ~~~~^~~~~~~~~~~\n",
            "TypeError: not all arguments converted during string formatting\n",
            "Call stack:\n",
            "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 88, in _run_code\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py\", line 37, in <module>\n",
            "    ColabKernelApp.launch_instance()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
            "    app.start()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py\", line 712, in start\n",
            "    self.io_loop.start()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py\", line 205, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n",
            "    self._run_once()\n",
            "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n",
            "    handle._run()\n",
            "  File \"/usr/lib/python3.11/asyncio/events.py\", line 84, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py\", line 510, in dispatch_queue\n",
            "    await self.process_one()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py\", line 499, in process_one\n",
            "    await dispatch(*args)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py\", line 406, in dispatch_shell\n",
            "    await result\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py\", line 730, in execute_request\n",
            "    reply_content = await reply_content\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py\", line 383, in do_execute\n",
            "    res = shell.run_cell(\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py\", line 528, in run_cell\n",
            "    return super().run_cell(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2975, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"/tmp/ipython-input-9-2758751736.py\", line 8, in <cell line: 0>\n",
            "    logging.error(\"I am handling zero division error\", e)\n",
            "Message: 'I am handling zero division error'\n",
            "Arguments: (ZeroDivisionError('division by zero'),)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#7 How do you log information at different levels(INFO,ERROR,WARNING) in python using the logging module ?\n",
        "\n",
        "import logging\n",
        "logging.basicConfig(filename = \"c.log\",level = logging.INFO )\n",
        "logging.info(\"This is my normal message\")\n",
        "logging.warning(\"This is my warning message\")\n",
        "logging.error(\"Some error occurs\")\n",
        "logging.shutdown()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "O112SMvZQljG",
        "outputId": "3c6ef2b1-c015-4095-cf6c-02f86d01fffc"
      },
      "execution_count": 27,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "WARNING:root:This is my warning message\n",
            "ERROR:root:Some error occurs\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#8 Write a program to handle a file opening error using exception handling?\n",
        "\n",
        "try:\n",
        "   f= open(\"b.txt\",\"r\")\n",
        "   f.read()\n",
        "except Exception as e:\n",
        "  print(\"first message---File is not opened due to\",e)\n",
        "except FileNotFoundError as e:\n",
        "   print(\"The following file was not created , please re run the code\",e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pndE50EXNaht",
        "outputId": "7a2d7994-b163-4828-9e15-9eeffaf22f24"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "first message---File is not opened due to [Errno 2] No such file or directory: 'b.txt'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#9 How can you read a file line by line and store its content in a list in python ?\n",
        "\n"
      ],
      "metadata": {
        "id": "B710bhu4NrJ1"
      },
      "execution_count": 13,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#10 #10 How can you append data to an exiting file in python ?\n",
        "\n",
        "with open(\"r.txt\",\"w\")as f:\n",
        "  f.write(\"1st line\\n\")\n",
        "  f.write(\"2nd line\\n\")\n",
        "  f.close()\n",
        "\n",
        "with open(\"r.txt\",\"a\")as f:\n",
        "   f.write(\"3rd line\\n\")\n",
        "\n",
        "with open(\"r.txt\",\"r\")as f:\n",
        "   print(f.read())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "32FMs0RxN2Eu",
        "outputId": "969e8436-db8a-4eca-d39a-472eb554890d"
      },
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "1st line\n",
            "2nd line\n",
            "3rd line\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#11 Write python program that uses a try-except block to handle an error when attempting to access a dictionary key that doesn't exist.\n",
        "\n",
        "try:\n",
        "  data = {\"name\":\"Sam\",\"course\":\"DS\",\"age\":22}\n",
        "  data[\"fee\"]\n",
        "except KeyError as e:\n",
        "   print(\"key is not found\",e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kdOcWQbOOIGu",
        "outputId": "ac4de49f-30cc-4700-d714-e62e03d77385"
      },
      "execution_count": 15,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "key is not found 'fee'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#12 Write a program that demonstrates using multiple except blocks to handle different types of exceptions.\n",
        "\n",
        "try: 10/\"a\"\n",
        "except ZeroDivisionError as e:\n",
        "   print(\"The division is not possible \",e)\n",
        "except Exception as e:\n",
        "     print(\"The error is\",e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "O1kGstYPPSp9",
        "outputId": "785fc331-7a1a-4606-8562-075b9e7d3417"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "The error is unsupported operand type(s) for /: 'int' and 'str'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#13 How do you check if a file exists before attempting to read it in python ?\n",
        "\n",
        "try:\n",
        "   file = open(\"new.txt\",\"r\")\n",
        "    line = file.read()\n",
        "    file.close()\n",
        "except FileNotFoundError as e:\n",
        "   print(\"Error:\",e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 106
        },
        "id": "mJhcPGF0PcMV",
        "outputId": "c3333204-6c09-4186-d543-e8641e5aed84"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "error",
          "ename": "IndentationError",
          "evalue": "unexpected indent (ipython-input-18-664171735.py, line 5)",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"/tmp/ipython-input-18-664171735.py\"\u001b[0;36m, line \u001b[0;32m5\u001b[0m\n\u001b[0;31m    line = file.read()\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unexpected indent\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#14 Write a program that uses logging module to log both informational and error messages.\n",
        "\n",
        "import logging\n",
        "logging.basicConfig(filename=\"m.log\", level=logging.INFO)\n",
        "logging.info(\"This is info\")\n",
        "logging.error(\"This is error\")\n",
        "logging.shutdown()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "q2Kbx12JPjpt",
        "outputId": "e0549ef8-df4c-4c44-b762-7e4ffa1facae"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "ERROR:root:This is error\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#15 Write a python program that prints the content of a file and handles the case when file is empty.\n",
        "\n",
        "try:\n",
        "  with open(\"e.txt\",\"r\")as file:\n",
        "     content = file.read()\n",
        "     if content:\n",
        "      print(content)\n",
        "     else:\n",
        "      print(\"The file is empty\")\n",
        "except FileNotFoundError as e:\n",
        "  print(\"file not found\", e)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wnZEkytHPz81",
        "outputId": "f86a64e6-9d79-4b26-d344-c06ea868d2e8"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "file not found [Errno 2] No such file or directory: 'e.txt'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "X3T4wKkxQVa2"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}